---
title: "W3 Section Exercise"
author: "your name here"
date: "2026-01-23"
output: html_document
---

1. I would like to simulate data from a few normal distributions with different means then generate a mean estimate for each. I wrote the following function, but it is not working as intended. "Debug" it.

```{r}
run <- function(n=200) {
  
  # Initiate
  i <- 0
  estimates <- c()
  
  # Specify function to run one simulation
  run_once <- function(i, mu_grid){
    mu <- mu_grid[i]
    y <- rnorm(n, mean = mu, sd = .1)
    est <- mean(y)
    
    i <- i + 1
    if (i > length(mu_grid)) i <- 0
    
    append(estimates, est) # Returns the new vector of estimates
  }
  
  # Call function to run one simulation and estimation
  run_once(i, mu_grid)
  
  estimates # Return the complete vector of estimates
}

# Run the simulation
set.seed(30600)
mu_grid <- seq(0, 0.75, 0.25)
run()
```

2. `for` loops help us avoid having to manually index like in the function above. Modify the code following each of these steps:

  a) Instead of function run, write a for-loop to call function run_once
  
  b) Instead of functions run and run_once, write a for-loop to conduct both data generation and estimation


3. Suppose we want to estimate both the mean and the variance of each draw.

  a) Modify the function such that it estimates and returns the variance alongside the mean. Write code to combine the two into a single dataframe or matrix.
  
  b) Instead of a for-loop, use functions in the base::lapply() family to execute the simulations and estimation for both mean and variance.
  
  c) Bonus: Instead of a for-loop or base::lappy, use functions in the purrr::map family to execute the simulations and estimation for both mean and variance.

